package edu.put.ma.descs.algorithms;

public enum ComparisonAlgorithmType {

    BACKTRACKING_DRIVEN_LONGEST_ALIGNMENT, 
    BACKTRACKING_DRIVEN_FIRST_ALIGNMENT_ONLY,
    HUNGARIAN_METHOD_DRIVEN_FIRST_ALIGNMENT_ONLY_PARTIAL_SOLUTIONS_NOT_CONSIDERED,
    HUNGARIAN_METHOD_DRIVEN_LONGEST_ALIGNMENT_PARTIAL_SOLUTIONS_NOT_CONSIDERED,
    HUNGARIAN_METHOD_DRIVEN_LONGEST_ALIGNMENT_PARTIAL_SOLUTIONS_CONSIDERED;

    
}
